import PushNotification from 'react-native-push-notification';

class Notification {
  constructor() {
    PushNotification.createChannel(
      {
        channelId: 'booking-success', // (required)
        channelName: 'Booking Success', // (required)
        channelDescription: 'Send notification when success create booking', // (optional) default: undefined.
      },
      created => console.log(`createChannel returned '${created}'`), // (optional) callback returns whether the channel was created, false means it already existed.
    );
  }

  bookingSuccessNotification() {
    PushNotification.localNotification({
      /* iOS and Android properties */
      //   id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      channelId: 'booking-success',
      title: 'Booking ticket success', // (optional)
      message: 'Please complete the payment process', // (required)
    });
  }

  scheduleNotification() {
    PushNotification.localNotification({
      /* iOS and Android properties */
      //   id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      channelId: 'booking-success',
      title: 'Just testing', // (optional)
      message: 'dont mind this notification', // (required)
    });
  }
}

export default new Notification();
