name: Android Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease --no-daemon

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.ALIAS }}
